// =========================================================================
// ARCHIVO: docentes.js (DICCIONARIO MAESTRO DE PERSONAL EN PRODUCCIÓN)
// Comisión de Planeamiento Institucional - UEF La Dolorosa
// =========================================================================

const DATA_DOCENTES = {
  "Amparo Pacheco": { "cedula": "1102718044", "nombre_completo": "PACHECO CARRION CARMEN AMPARO", "titulo": "Licenciada" },
  "Ana Guanin": { "cedula": "1105905820", "nombre_completo": "GUANIN MEDINA ANA VALERIA", "titulo": "Licenciada" }, // <-- Datos de Ana corregidos
  "Ana Holguin": { "cedula": "1308668605", "nombre_completo": "HOLGUIN INTRIAGO ANA RAMONA", "titulo": "Licenciada" },
  "Andrea Moncayo": { "cedula": "1104227770", "nombre_completo": "MONCAYO VASQUEZ ANDREA KATHERINE", "titulo": "Ingeniera" },
  "Andrea Ochoa": { "cedula": "1104708373", "nombre_completo": "OCHOA CASTILLO ANDREA MAGALY", "titulo": "Ingeniera" },
  "Angelica Cabrera": { "cedula": "1104361124", "nombre_completo": "CABRERA GUZMAN ANGELICA MARIBEL", "titulo": "Licenciada" },
  "Astrid Armijos": { "cedula": "1102846894", "nombre_completo": "ARMIJOS VIVANCO ASTRID ASUNCION", "titulo": "Licenciada" },
  "Bolivar Camacho": { "cedula": "1103384077", "nombre_completo": "CAMACHO MUÑOZ BOLIVAR VICENTE", "titulo": "Ingeniero" },
  "Bolívar Martínez": { "cedula": "1103036867", "nombre_completo": "MARTINEZ ALVAREZ JOSE BOLIVAR", "titulo": "Licenciado" },
  "Carlos Rivas": { "cedula": "1104239148", "nombre_completo": "RIVAS HERRERA CARLOS ALBERTO", "titulo": "Licenciado" },
  "Carmen España": { "cedula": "1103393060", "nombre_completo": "ESPAÑA MINGA CARMEN PATRICIA", "titulo": "Licenciada" },
  "Danny Azanza": { "cedula": "1104608292", "nombre_completo": "AZANZA VILLACIS DANNY XAVIER", "titulo": "Abogado" },
  "Dennis Lima": { "cedula": "1103638829", "nombre_completo": "LIMA CUEVA DENISSE DEL ROSARIO", "titulo": "Ingeniera" },
  "Diana Pacheco": { "cedula": "1103010045", "nombre_completo": "PACHECO SERAQUIVE DIANA ELIZABETH", "titulo": "Ingeniera" },
  "Diana Simancas": { "cedula": "1104090137", "nombre_completo": "SIMANCAS MEDINA DIANA DEL CARMEN", "titulo": "Licenciada" },
  "Edilma Alulima": { "cedula": "1103059166", "nombre_completo": "ALULIMA GUAMO EDILMA IRALDA", "titulo": "Licenciada" },
  "Edwin Sosoranga": { "cedula": "1103769418", "nombre_completo": "SOZORANGA BENITEZ EDWIN MARCELO", "titulo": "Ingeniero" },
  "Elaine Abrigo": { "cedula": "1104611593", "nombre_completo": "ABRIGO TITUANA ELAINE JUDITH", "titulo": "Licenciada" },
  "Enith Girón": { "cedula": "1713641650", "nombre_completo": "GIRON PARDO ENITH SEBASTIANA", "titulo": "Licenciada" },
  "Fabián Cueva": { "cedula": "1102772306", "nombre_completo": "CUEVA ROMERO FABIAN EDUARDO", "titulo": "Doctor" },
  "Gabriela Correa": { "cedula": "1104241979", "nombre_completo": "CORREA TINOCO GABRIELA MIRIEL", "titulo": "Ingeniera" },
  "Gabriela Rivera": { "cedula": "1718517210", "nombre_completo": "RIVERA QUILLIGANA NANCY GABRIELA", "titulo": "Licenciada" },
  "Gerardo Chocho": { "cedula": "1104103369", "nombre_completo": "CHOCHO ZAPATA GERARDO ALBERTO", "titulo": "Licenciado" },
  "Giovanna Salinas": { "cedula": "1104776495", "nombre_completo": "SALINAS PAUTA GIOVANNA ALEXANDRA", "titulo": "Abogada" },
  "Hna. Cecilia Vera": { "cedula": "1304934779", "nombre_completo": "VERA GONZALEZ ANA ROSA", "titulo": "Licenciada" },
  "Ivan Sarango": { "cedula": "1102723291", "nombre_completo": "SARANGO SANDOVAL MAXIMO IVAN", "titulo": "Licenciado" },
  "Jaime Bustos": { "cedula": "1102819768", "nombre_completo": "BUSTOS SAMANIEGO JAIME SERVILIO", "titulo": "Doctor" },
  "Janela Plaza": { "cedula": "1104220619", "nombre_completo": "PLAZA MEDINA JANELA DEL PILAR", "titulo": "Licenciada" },
  "Jessica Granda": { "cedula": "0703989541", "nombre_completo": "GRANDA CISNEROS JESSICA ALEXANDRA", "titulo": "Licenciada" },
  "Jimmy Tandazo": { "cedula": "1102739289", "nombre_completo": "TANDAZO ARIAS JIMMY HANDEL", "titulo": "Doctor" },
  "Jorge Sarmiento Z": { "cedula": "1103829865", "nombre_completo": "SARMIENTO ZUMBA JORGE ROLANDO", "titulo": "Magíster" },
  "Jose Luis Hernández": { "cedula": "1103417265", "nombre_completo": "HERNANDEZ SARMIENTO JOSE LUIS", "titulo": "Licenciado" },
  "Juan Carlos Ramos.": { "cedula": "1104872344", "nombre_completo": "RAMOS PARDO JUAN CARLOS", "titulo": "Licenciado" }, // <-- Datos de Juan Carlos corregidos
  "Karla Monteros": { "cedula": "1102390380", "nombre_completo": "MONTEROS CUEVA KARLA ESMERALDA", "titulo": "Licenciada" },
  "Kelvin Alulima": { "cedula": "1103734099", "nombre_completo": "ALULIMA CARRION KELVÍN ARMANDO", "titulo": "Licenciado" }, // <-- Datos de Kelvín corregidos
  "Leonardo Jimenez": { "cedula": "1103507289", "nombre_completo": "JIMENEZ CUENCA LEONARDO VINICIO", "titulo": "Ingeniero" },
  "Lorena León": { "cedula": "1102871140", "nombre_completo": "LEON CORONEL LORENA ALEXANDRA", "titulo": "Licenciada" },
  "Lourdes Jacome": { "cedula": "0913043907", "nombre_completo": "JACOME ALARCON ANGELA DE LOURDES", "titulo": "Licenciada" },
  "Margarita Sarango": { "cedula": "1104053903", "nombre_completo": "SARANGO SOTO MARGARITA LUCIA", "titulo": "Ingeniera" },
  "Maria Espinoza": { "cedula": "1103641088", "nombre_completo": "ESPINOSA SEMPERTEGUI MARIA ALEJANDRA", "titulo": "Ingeniera" },
  "Marianela Retete": { "cedula": "1104611221", "nombre_completo": "RETETE OCHOA MARIANELA DEL CISNE", "titulo": "Licenciada" },
  "Mario Sánchez": { "cedula": "1103304661", "nombre_completo": "SANCHEZ ARMIJOS MARIO AGUSTO", "titulo": "Licenciado" },
  "Marlene Gualán": { "cedula": "1103554679", "nombre_completo": "GUALAN AJILA MARLENE ESPERANZA", "titulo": "Licenciada" },
  "Nely Jaramillo": { "cedula": "1104331655", "nombre_completo": "JARAMILLO GODOY NELY VICENTA", "titulo": "Ingeniera" },
  "Patricia Hernández": { "cedula": "1102651013", "nombre_completo": "HERNANDEZ SARMIENTO PATRICIA SOLEDAD", "titulo": "Licenciada" },
  "Patricio Espinoza": { "cedula": "1102765243", "nombre_completo": "ESPAÑA PEDRO PATRICIO", "titulo": "Doctor" },
  "Paula Armijos": { "cedula": "1106067026", "nombre_completo": "ARMIJOS IÑIGUEZ PAULA MICHELLE", "titulo": "Licenciada" },
  "Paula Gordillo": { "cedula": "1104093826", "nombre_completo": "GORDILLO IÑIGUEZ PAULA XIMENA", "titulo": "Ingeniera" },
  "Roberto Pineda": { "cedula": "1102884119", "nombre_completo": "PINEDA BAILON ROBERTO VINICIO", "titulo": "Ingeniero" },
  "Rodolfo Carrera": { "cedula": "1104452972", "nombre_completo": "CARRERA ENCALADA RODOLFO VICENTE", "titulo": "Licenciado" },
  "Rubier Ramos": { "cedula": "1103111611", "nombre_completo": "RAMOS RENTERIA RUBIER FRANCISCO", "titulo": "Licenciado" },
  "Ruth Guayanay": { "cedula": "1104796261", "nombre_completo": "GUAYANAY CHINCHAY RUTH ENITH", "titulo": "Licenciada" },
  "Ruth Montaño": { "cedula": "1103086516", "nombre_completo": "MONTAÑO GONZALEZ RUTH PAULINA", "titulo": "Licenciada" },
  "Santiago Ramón": { "cedula": "1104678162", "nombre_completo": "RAMON CALVACHE SANTIAGO JAVIER", "titulo": "Licenciado" },
  "Sonia Armijos": { "cedula": "1709463242", "nombre_completo": "ARMIJOS GUZMAN SONIA YAQUELINE", "titulo": "Doctora" },
  "Verónica Ruilova": { "cedula": "1103392013", "nombre_completo": "RUILOVA BLACIO VERONICA MARIA", "titulo": "Licenciada" },
  "Victor Maldonado": { "cedula": "1102931506", "nombre_completo": "MALDONADO RIVERA VICTOR HUGO", "titulo": "Doctor" },
  "Yaritza Marín": { "cedula": "1103747323", "nombre_completo": "MARIN JUMBO YARITZA DEL CISNE", "titulo": "Ingeniera" }
};
